version: '3'

services:
  app:
    build:
      context: ./adminpanel
    container_name: photobooth_adminpanel_app
    env_file:
      - .env
    restart: always
    networks:
      default:

  bot:
    build:
      context: ./bot
    container_name: photobooth_adminpanel_bot
    env_file:
      - .env
    restart: always
    networks:
      default:

  redis:
    image: redis:alpine
    container_name: photobooth_adminpanel_redis
    restart: always
    networks:
      default:
    ports:
      - "6379:6379"

